// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package errs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindInternal-0]
	_ = x[KindUnauthorized-1]
	_ = x[KindLoginPassword-2]
	_ = x[KindForbidden-3]
	_ = x[KindNotFound-4]
	_ = x[KindConflict-5]
	_ = x[KindDuplicate-6]
	_ = x[KindParameterErr-7]
	_ = x[KindTooManyRequests-8]
	_ = x[KindDependentService-9]
	_ = x[KindBlocked-10]
}

const _Kind_name = "KindInternalKindUnauthorizedKindLoginPasswordKindForbiddenKindNotFoundKindConflictKindDuplicateKindParameterErrKindTooManyRequestsKindDependentServiceKindBlocked"

var _Kind_index = [...]uint8{0, 12, 28, 45, 58, 70, 82, 95, 111, 130, 150, 161}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
