@baseURL = http://localhost:8088

# @name addversion
POST {{baseURL}}/v2/version HTTP/1.1

{
	"id": "demo_app",
	"code" : "99",
	"package" : "com.ios.zeyad"
}
###

# @name getversion
GET {{baseURL}}/v2/version/demo_app HTTP/1.1
###

# @name updateversion
PUT {{baseURL}}/v2/version/demo_app HTTP/1.1

{
	"id": "demo_app",
	"package" : "com.ios.zeyad.new"
}
###

# @name listversions
GET {{baseURL}}/v2/version HTTP/1.1
